language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
install:
  - "pip install ."
  - "pip install -r test-requirements.txt"
  - "pip install coveralls"
before_script: python setup.py flake8
script: coverage run setup.py test && coverage report --fail-under=100
after_success: coveralls
